[package]
authors = ["The Rust Project Developers"]
name = "rustc_jobserver"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustc_jobserver"
path = "lib.rs"
doctest = false

[dependencies]
jobserver_crate = { version = "0.1.13", package = "jobserver" }
lazy_static = "1"
